# wrangler.toml
name = "mediswiss-ai-worker"
main = "src/worker.js"
compatibility_date = "2024-01-06"

# Enable logging
[observability.logs]
enabled = true

# Public variables
[vars]
API_URL = "https://mediswiss.ai/wp-json/custom/v1"